version: '3.7'
services:
  strapi:
    image: strapi/strapi
    ports:
      - "1337:1337"
    volumes:
      - ./strapi:/srv/app
    restart: always
    networks:
    - rocktver-network


  #frontend:
  #  container_name: svelte
  #  build:
  #    context: ./frontend
  #    dockerfile: ./Dockerfile
  #  ports:
  #    - "3000:3000"
    #depends_on:
    #  - backend

  ghost:
    image: ghost:latest
    restart: always
    ports:
      - "2368:2368"
    volumes:
    #  - ./data-ghost-content/config.production.json:/var/lib/ghost/config.production.json:z #overwrite default settings 
      - ./data-ghost-content:/var/lib/ghost/content
    networks:
    - rocktver-network

  node-red:
    container_name: node-red
    build:
      context: .
      dockerfile: ./nodered2.Dockerfile
    #env_file: .env
    ports:
      - "1880:1880"
    networks:
      - rocktver-network
    depends_on:
      - redis
    volumes:
      - ./node-red-data:/data 
    restart: always

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass YzRAdGgkFg
    ports:
     - "6379:6379"
    environment:
         - REDIS_REPLICATION_MODE=master
    volumes:
      - ./redis-data:/data
    restart: always
    networks:
      - rocktver-network


volumes:
  node-red-data:
  data-ghost-content:

networks:
  rocktver-network:
    driver: bridge
